import { EventConfig, AttendeeProfile, Speaker, DirectoryAttendee, PostTemplate } from './types';

export const INITIAL_EVENT_CONFIG: EventConfig = {
  name: 'Global AI & Cloud Architecture Summit 2025',
  date: 'Oct 24, 2025',
  timeFormat: '09:00 AM PST • Hybrid (San Francisco & Virtual)',
  theme: 'Scaling Enterprise AI with Responsible Governance, Autonomous Agent Architectures & Real-World Enterprise Migration Case Studies.',
  topics: ['Generative AI', 'LLM Ops & Agents', 'Cloud Infrastructure', 'Security & Governance'],
  audience: 'Engineering Leaders, AI Founders, Cloud Architects',
  hashtags: '#GlobalAISummit2025 #CloudSummit #PostSparkAI',
  linkedInUrl: 'https://linkedin.com/events/global-ai-cloud-summit-7249102830',
  autoApprove: true,
  campaignStatus: 'Active Draft',
  activePhase: 'pre',
  attendeesTracked: 342,
  postsGenerated: 89,
  reachMultiplier: '4.8x',
};

export const INITIAL_ATTENDEE_PROFILE: AttendeeProfile = {
  name: 'Sarah Jenkins',
  role: 'VP of Product Engineering',
  company: 'TechNova Solutions',
  location: 'San Francisco, CA',
  passId: 'Pass #AIS-8841',
  photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFjuczMEVfH2YwhQmQSyWNJLUl9TP8SX-NsiSKFlsI3R77jtxRdwAnwaOh93GTJ51ksGy6v-57mN8L6YrRLeWanUaHhL2hL62ZGrcYJWmXSxSFuRZjmDZkfhk1RvBs30k81sHiGZpJwpjEQG8-1ldW5Wz_Vak7WsFBSgxCdh2Us-m9pDcPJAjv6qCD-8Bv883AclgrGbVbv3R1tddGR-yOUkxx-cU55wO2zmo1KE18MDCIVgCpKpjg',
  filename: 'sarah_jenkins_headshot.jpg',
  fileSize: '1.4 MB',
};

export const POSTSPARK_LOGO_URL = 'https://lh3.googleusercontent.com/aida/AEtjO1UMVoGRLwLo_2FMStRwGrpKhGiOnpWhtyRfLf1_hqUDlshH2dMR3No45_xqmzEky_51e1274v-orvNgaiiZR0CSkyBdaGW6nUdz5nxG9DsAjyghImukDkQdE2K9TXQtYcd4soU9LcsuxCSQ1vyCj8NPhWRXhfqEBWqnKi1TrAC_pP86_qLxLQOQO7FCf5IitO3iKLqs4LMMRlfq67KoCx7mEBtZeURKoCGAwH6YIGc1GmjleB44YIxbd5I';

export const PRESET_AVATARS = [
  {
    name: 'Sarah Jenkins',
    role: 'VP of Product Engineering @ TechNova Solutions',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFjuczMEVfH2YwhQmQSyWNJLUl9TP8SX-NsiSKFlsI3R77jtxRdwAnwaOh93GTJ51ksGy6v-57mN8L6YrRLeWanUaHhL2hL62ZGrcYJWmXSxSFuRZjmDZkfhk1RvBs30k81sHiGZpJwpjEQG8-1ldW5Wz_Vak7WsFBSgxCdh2Us-m9pDcPJAjv6qCD-8Bv883AclgrGbVbv3R1tddGR-yOUkxx-cU55wO2zmo1KE18MDCIVgCpKpjg',
    filename: 'sarah_jenkins_headshot.jpg',
    size: '1.4 MB',
  },
  {
    name: 'Elena Vance',
    role: 'VP of Cloud AI @ Datastream Systems',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCNIN6xwe_RNZrGtYBEZ38zK67utUVva0jBBzjc6Yd9Tu7SG_MNS7N4KS2MUf85F6T2IrZap6vZ2NhGQ927Xs86HO-VMxvgTAnm9JNh_mqwngYcNU0L3ma2qrvWLbS1yLNkmQ4FPy6PIttsLxGUUffrtec5ImiU2oL6niZ0D_MZbgUi-FEMGHR-p9tLfdLMZpU7wtM91aHK4j3GHgy8dpcBO0hQg5t5YoWMgPifD7Pp6vATSvRoddp3',
    filename: 'elena_vance_exec.jpg',
    size: '2.1 MB',
  },
  {
    name: 'Marcus Chen',
    role: 'Chief Architect @ QuantumGrid Labs',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeiIl1uI-syHO1utUx8iRkNMjoYL8pslFKswjnVm1I71LkgKZnaT0LGgY9FuuMXlcs7Jnf-i8FRYDYoKwl2Ho8bRrvlczIDF29KBTUw2Z_VlygUgC9Hipf9QV0MWoGE5t9Pv4ZWl_XvI06HN2eC8DeJ-BboIl2WxEcp_G0uW7OUlnUH3jGUhDGiPOw8m4Xq9a3u_uNmjbJcsWkgilWCF8LfzaShzZPuDDMkSmbqbY_5GP6Ch-3LVaa',
    filename: 'marcus_chen_headshot.png',
    size: '1.8 MB',
  },
  {
    name: 'Amara Okafor',
    role: 'Head of Responsible AI & Governance',
    url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    filename: 'amara_okafor_portrait.jpg',
    size: '1.6 MB',
  },
  {
    name: 'David Lindqvist',
    role: 'Staff ML Infrastructure Engineer',
    url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    filename: 'david_lindqvist_tech.jpg',
    size: '1.9 MB',
  },
  {
    name: 'Maya Patel',
    role: 'Founder & CEO @ AgenticFlow',
    url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    filename: 'maya_patel_ceo.jpg',
    size: '1.2 MB',
  },
];

export const SPEAKERS_LIST: Speaker[] = [
  {
    id: 'spk-1',
    name: 'Marcus Chen',
    role: 'Chief Architect',
    company: 'QuantumGrid Labs',
    topic: 'Zero-Downtime Migrations to Distributed LLM Clusters',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeiIl1uI-syHO1utUx8iRkNMjoYL8pslFKswjnVm1I71LkgKZnaT0LGgY9FuuMXlcs7Jnf-i8FRYDYoKwl2Ho8bRrvlczIDF29KBTUw2Z_VlygUgC9Hipf9QV0MWoGE5t9Pv4ZWl_XvI06HN2eC8DeJ-BboIl2WxEcp_G0uW7OUlnUH3jGUhDGiPOw8m4Xq9a3u_uNmjbJcsWkgilWCF8LfzaShzZPuDDMkSmbqbY_5GP6Ch-3LVaa',
    isKeynote: true,
  },
  {
    id: 'spk-2',
    name: 'Elena Vance',
    role: 'VP of Cloud AI',
    company: 'Datastream Systems',
    topic: 'Governance Standards for Autonomous Enterprise Agent Swarms',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCNIN6xwe_RNZrGtYBEZ38zK67utUVva0jBBzjc6Yd9Tu7SG_MNS7N4KS2MUf85F6T2IrZap6vZ2NhGQ927Xs86HO-VMxvgTAnm9JNh_mqwngYcNU0L3ma2qrvWLbS1yLNkmQ4FPy6PIttsLxGUUffrtec5ImiU2oL6niZ0D_MZbgUi-FEMGHR-p9tLfdLMZpU7wtM91aHK4j3GHgy8dpcBO0hQg5t5YoWMgPifD7Pp6vATSvRoddp3',
    isKeynote: true,
  },
  {
    id: 'spk-3',
    name: 'Dr. Aris Thorne',
    role: 'Director of AI Research',
    company: 'Hyperion Labs',
    topic: 'Context Compression & Multi-Vector Caching in Production',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    isKeynote: false,
  },
  {
    id: 'spk-4',
    name: 'Priya Patel',
    role: 'VP of Infrastructure',
    company: 'CloudScale Global',
    topic: 'SRE Playbooks for GPU Cluster Resiliency at Scale',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    isKeynote: false,
  },
];

export const DIRECTORY_ATTENDEES: DirectoryAttendee[] = [
  {
    id: 'att-1',
    name: 'Elena Vance',
    role: 'VP of Cloud AI',
    company: 'Datastream Systems',
    location: 'San Francisco, CA',
    passId: 'Pass #AIS-1042',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCNIN6xwe_RNZrGtYBEZ38zK67utUVva0jBBzjc6Yd9Tu7SG_MNS7N4KS2MUf85F6T2IrZap6vZ2NhGQ927Xs86HO-VMxvgTAnm9JNh_mqwngYcNU0L3ma2qrvWLbS1yLNkmQ4FPy6PIttsLxGUUffrtec5ImiU2oL6niZ0D_MZbgUi-FEMGHR-p9tLfdLMZpU7wtM91aHK4j3GHgy8dpcBO0hQg5t5YoWMgPifD7Pp6vATSvRoddp3',
    postPreview: "Excited to announce I'll be attending the #GlobalAISummit2025 in SF this October! Looking forward to diving into autonomous agent governance and real-world enterprise LLM architectures. Who else from my network will be there? Let's connect! 🚀",
    reactions: 142,
    comments: 28,
    sharedAt: '22m ago',
    badgeType: 'Attendee',
    phase: 'pre',
  },
  {
    id: 'att-2',
    name: 'Marcus Chen',
    role: 'Chief Architect',
    company: 'QuantumGrid Labs',
    location: 'Seattle, WA',
    passId: 'Pass #AIS-0012',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeiIl1uI-syHO1utUx8iRkNMjoYL8pslFKswjnVm1I71LkgKZnaT0LGgY9FuuMXlcs7Jnf-i8FRYDYoKwl2Ho8bRrvlczIDF29KBTUw2Z_VlygUgC9Hipf9QV0MWoGE5t9Pv4ZWl_XvI06HN2eC8DeJ-BboIl2WxEcp_G0uW7OUlnUH3jGUhDGiPOw8m4Xq9a3u_uNmjbJcsWkgilWCF8LfzaShzZPuDDMkSmbqbY_5GP6Ch-3LVaa',
    postPreview: "Honored to keynote at Global AI & Cloud Architecture Summit 2025! I'll be breaking down zero-downtime migrations to distributed LLM clusters. Grab your ticket via the link below: #CloudSummit",
    reactions: 318,
    comments: 54,
    sharedAt: '1h ago',
    badgeType: 'Speaker',
    phase: 'pre',
  },
  {
    id: 'att-3',
    name: 'Sarah Jenkins',
    role: 'VP of Product Engineering',
    company: 'TechNova Solutions',
    location: 'San Francisco, CA',
    passId: 'Pass #AIS-8841',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFjuczMEVfH2YwhQmQSyWNJLUl9TP8SX-NsiSKFlsI3R77jtxRdwAnwaOh93GTJ51ksGy6v-57mN8L6YrRLeWanUaHhL2hL62ZGrcYJWmXSxSFuRZjmDZkfhk1RvBs30k81sHiGZpJwpjEQG8-1ldW5Wz_Vak7WsFBSgxCdh2Us-m9pDcPJAjv6qCD-8Bv883AclgrGbVbv3R1tddGR-yOUkxx-cU55wO2zmo1KE18MDCIVgCpKpjg',
    postPreview: "Excited to announce I'll be attending the Global AI & Cloud Summit 2025 in San Francisco this October! 🚀 Looking forward to deep-diving into practical autonomous agent architectures and learning how leading engineering teams are scaling resilient LLM applications in production. Will you be there? Let's connect or grab a coffee!",
    reactions: 84,
    comments: 16,
    sharedAt: 'Just now',
    badgeType: 'Attendee',
    phase: 'pre',
  },
  {
    id: 'att-4',
    name: 'Amara Okafor',
    role: 'Head of Responsible AI & Governance',
    company: 'Sovereign Intelligence',
    location: 'San Francisco, CA',
    passId: 'Pass #AIS-2490',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    postPreview: "What an exhilarating 3 days at #GlobalAISummit2025! 🌟 Key takeaways from the governance stage: 1. Autonomous agent guardrails must be deterministic, not statistical. 2. Real-time observability beats post-hoc audit logs every time. Huge gratitude to the organizers and all the builders who shared their war stories. See you all in 2026!",
    reactions: 215,
    comments: 42,
    sharedAt: '4h ago',
    badgeType: 'Attendee',
    phase: 'post',
  },
  {
    id: 'att-5',
    name: 'David Lindqvist',
    role: 'Staff ML Infrastructure Engineer',
    company: 'ScaleNative',
    location: 'Stockholm & SF',
    passId: 'Pass #AIS-3918',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    postPreview: "Post-summit debrief: Packed Moscone room for our session on distributed GPU caching! Slides and architecture diagrams are now uploaded (link in comments). Inspiring conversations with 30+ enterprise teams rethinking their inference stacks. #GlobalAISummit #CloudSummit",
    reactions: 189,
    comments: 31,
    sharedAt: '6h ago',
    badgeType: 'Speaker',
    phase: 'post',
  },
];

export const POST_TEMPLATES: PostTemplate[] = [
  // PRE-EVENT TEMPLATES
  {
    id: 'tmpl-pre-1',
    title: 'Pre-Event: Executive Pass Announcement',
    category: 'Attendee',
    phase: 'pre',
    recommendedTone: 'thought_leader',
    description: 'High-credibility pre-summit announcement positioning you as an engineering leader anticipating key summit breakthroughs.',
    previewSnippet: "Excited to announce I'll be attending the Global AI & Cloud Summit 2025 in San Francisco this October! 🚀 Looking forward to deep-diving into practical autonomous agent architectures...",
  },
  {
    id: 'tmpl-pre-2',
    title: 'Pre-Event: Keynote & Speaker Session Teaser',
    category: 'Speaker',
    phase: 'pre',
    recommendedTone: 'speaker',
    description: 'Authoritative pre-event talk teaser designed to maximize session room fill and audience engagement.',
    previewSnippet: "Humbled and thrilled to take the stage at Global AI & Cloud Summit 2025! 🎙️ I'll be unpacking practical lessons from scaling multi-agent systems without breaking latency budgets...",
  },
  {
    id: 'tmpl-pre-3',
    title: 'Pre-Event: Casual Networking & Coffee Meetup',
    category: 'Attendee',
    phase: 'pre',
    recommendedTone: 'casual',
    description: 'Warm, approachable pre-event post rallying friends, former colleagues, and industry peers to meet up in SF.',
    previewSnippet: "Heading to San Francisco for #GlobalAISummit2025! 🎉 Can't wait to catch up with old friends, meet new collaborators, and see what everyone is building. Pour-overs on me!",
  },
  {
    id: 'tmpl-pre-4',
    title: 'Pre-Event: Sponsor & Expo Booth Invitation',
    category: 'Sponsor',
    phase: 'pre',
    recommendedTone: 'direct',
    description: 'Direct invitation to visit booth demo stations, meet the founders, and claim exclusive summit swag.',
    previewSnippet: "Our team is on the ground at Global AI & Cloud Summit 2025! Come stop by Booth #412 to test our live multi-agent deployment sandbox and chat with our core engineering team.",
  },

  // POST-EVENT TEMPLATES
  {
    id: 'tmpl-post-1',
    title: 'Post-Event: Top 3 Takeaways & Debrief',
    category: 'Attendee',
    phase: 'post',
    recommendedTone: 'thought_leader',
    description: 'High-impact post-event recap synthesizing the most valuable technical learnings and architectural shifts from the summit.',
    previewSnippet: "What an incredible 3 days at #GlobalAISummit2025 in San Francisco! 💡 Here are my top 3 takeaways on how enterprise teams are operationalizing autonomous agents at scale...",
  },
  {
    id: 'tmpl-post-2',
    title: 'Post-Event: Speaker Slides & Session Recording',
    category: 'Speaker',
    phase: 'post',
    recommendedTone: 'speaker',
    description: 'Post-talk follow-up thanking the attendees and sharing presentation deck slides, GitHub repos, and video links.',
    previewSnippet: "Thank you to everyone who packed the room for my keynote on 'Zero-Downtime Agent Migrations' at Global AI Summit! 🎙️ As promised, I've linked the full slide deck and benchmark repo below 👇",
  },
  {
    id: 'tmpl-post-3',
    title: 'Post-Event: Gratitude & Community Shoutout',
    category: 'Attendee',
    phase: 'post',
    recommendedTone: 'casual',
    description: 'Heartfelt post-summit recap celebrating hallway chats, new connections, and giving a shoutout to organizers.',
    previewSnippet: "Home from SF with a full notebook and so much energy! 🚀 Huge shoutout to the #GlobalAISummit organizers for pulling off a stellar event. So great reconnecting with everyone—let's keep building!",
  },
  {
    id: 'tmpl-post-4',
    title: 'Post-Event: Executive Trend Synthesis',
    category: 'VIP',
    phase: 'post',
    recommendedTone: 'direct',
    description: 'Concise executive debrief designed for team Slack channels and LinkedIn peer networks.',
    previewSnippet: "Quick 2-minute executive debrief from Global AI & Cloud Summit 2025: 1. Multi-agent workflows are replacing monolithic prompts. 2. GPU caching is the new CDN. 3. Security governance is day-one priority.",
  },
];
